spring.application.name=condominios-api
spring.datasource.url=jdbc:mysql://localhost:3306/condominios
spring.datasource.username=root
spring.datasource.password=Chechar1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8084

# JWT
jwt.secret=A9fK72mQx8LpB3zTn4VwC1rS0yGhD6Xe
jwt.access-token-expiration-ms=900000       
jwt.refresh-token-expiration-ms=604800000   